### ISSUE TITLE
Sending events on `exit` throws if the machine is stopped

### ISSUE THREAD

**Issue by rlaffers** [statelyai/xstate#2450]
**Description**
The `send` action used as an exit action throws an error when the machine is stopped.

**Expected Result**
`send` in the `exit` actions should just send the event. If the target actor (e.g. the machine itself) is stopped already, the event should be ignored.
```javascript
const childMachine = createMachine({
  id: "child",
  initial: "Ready",
  states: {
    Ready: {
      entry: send("ENTERED"),
      exit: send("EXITED")
    }
  },
  on: {
    "*": {
      actions: (c, e) => console.log("event received", e)
    }
  }
});

const machine = createMachine({
  id: "root",
  initial: "Ready",
  states: {
    Ready: {
      invoke: {
        src: childMachine
      },
      on: {
        EXIT: "Done"
      }
    },
    Done: {
      type: "final"
    }
  }
});

const service = interpret(machine);
service.start();
service.send("EXIT"); // stops the child machine. The exit action in the child machine executes, but fails.
```

**Actual Result**
When the machine sends an event to itself when it was stopped, an error is thrown:
`TypeError
Cannot use 'in' operator to search for '$$type' in undefined
toSCXMLEvent
https://s3sgo.csb.app/node_modules/xstate/es/utils.js:693:38`

**Reproduction**
https://codesandbox.io/s/brave-frog-s3sgo

**Additional context**
Hint: When the send action is executed on exiting a state node, while the whole machine stops (e.g. on unmounting of the React component using the machine), the send action object is missing the internal `_event` property, which later causes the exception:
```javascript
// Interpreter.prototype.exec contains this line
this.send(sendAction._event); // _event is undefined
```

**Comment by davidkpiano** [comment]
Related: https://github.com/statelyai/xstate/issues/2057

**Comment by Andarist** [comment]
> the send action object is missing the internal _event property, which later causes the exception:

This is because those actions here never get "resolved":
https://github.com/statelyai/xstate/blob/10944fa6195a3146c7c120d7c3c5c5defeff4e72/packages/core/src/interpreter.ts#L519-L523

That is definitely a bug. What should happen when a machine is being stopped and the target actor is stopped already? In this particular situation those probably just act as noops, conceptually they should be treated as dead letters: https://doc.akka.io/docs/akka/current/general/message-delivery-reliability.html#dead-letters

**Comment by rlaffers** [comment]
Well, it would be nice to have those events logged somewhere (either in a synthetic dead letters actor, or just like any other event on  the target actor). If the target actor is stopped, it can just simply ignore the event.
By the way, in my case above, the event is being sent to the machine itself, so there an additional conundrum: if the source actor is being stopped, should it even send the event? It all comes down to the internal timing. What's first? Executing the exit action, then stopping - or vice versa?

**Comment by davidkpiano** [comment]
For reference, the [`exitInterpreter` procedure](https://www.w3.org/TR/scxml/#exitInterpreter) in the SCXML algorithm exits active states when the interpreter is exited/stopped, so this is the expected behavior.

Regarding the original issue, a "dead letter actor" can be considered; another related solution is handling `error.communication` events (or ignoring them): https://github.com/statelyai/xstate/pull/2883

**Comment by davidkpiano** [comment]
Addressed in #2903

**Comment by Andarist** [comment]
@davidkpiano this PR addresses a different problem. I have a branch locally to fix this one though - but I still need to write tests for it.

**Comment by erikras** [comment]
'sup team. I just ran into this bug. Child machine wanted to `sendParent` on `exit` of a state. When the whole system, including parent and child is shutting down, it caused an exception.

My fix: Because the state that was sending this on `exit` is one of two "toggle" states, I just put the `sendParent` on the `entry` of its opposite state.

**Comment by Andarist** [comment]
@erikras expect it to be fixed in Feb

**Comment by Jimmy89** [comment]
> @erikras expect it to be fixed in Feb

Do you have an update on this? I see the MR is merged into main, but the change is not mentioned in release v4.30.0 and the problem still occurs.

**Comment by Andarist** [comment]
@Jimmy89 I've switched gears to working on the core of XState almost exclusively. This problem is very high on my todo list so I would expect this to be fixed next week or so.
